image: gcc:6.5

pipelines:
  default:
    - step:
        script:
          - uname -a
          - gcc --version
          - apt-get update
          - apt-get install cmake doxygen graphviz libblas-dev liblapack-dev -y --force-yes
          - cmake --version
          - mkdir build
          - cd build
          - cmake .. -D CMAKE_BUILD_TYPE=Debug -D OPTION_BUILD_DOCS=ON
          - make
          - ./run_tests
