image: ubuntu

pipelines:
  default:
    - step:
        script:
          - uname -a
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive
          - apt-get install -y tzdata
          - apt-get install build-essential -y --force-yes
          - gcc --version
          - apt-get install git cmake doxygen graphviz libblas-dev liblapack-dev -y --force-yes
          - cmake --version
          - mkdir build
          - cd build
          - cmake -DCMAKE_BUILD_TYPE=Debug -DOPTION_BUILD_DOCS=ON ..
          - make
          - ./run_tests
          - make examples
