image: gcc:6.5

pipelines:
  default:
    - step:
        script:
          - uname -a
          - gcc --version
          - echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial main' | tee -a /etc/apt/sources.list.d/cmake.list
          - apt-get update -qq
          - apt-get install cmake libpthread-stubs0-dev doxygen graphviz libblas-dev liblapack-dev -y --force-yes
          - cmake --version
          - mkdir build
          - cd build
          - cmake .. -D CMAKE_BUILD_TYPE=Debug -D OPTION_BUILD_DOCS=ON
          - make
          - ./run_tests
